 #%RAML 1.0
title: RetrieveConsolidatedRoutesAndSchedules BAPI
description: This RAML file will retrieve consolidated routes and schedules for Process API

uses:
  common: /libraries/common/commonBusiness-library.raml
  route: /libraries/routes/routesBusiness-library.raml
  schedule: /libraries/schedule/schedulesBusiness-library.raml


/booking:
  /{transportType}:
    /routes:
      get:
        is:
          - common.transactionId
          - common.companyName
          - common.departureLocation
          - common.destinationLocation
        responses:
          200:
            body:
              application/json:
                type: route.getRoutesResponse
                example: !include /libraries/routes/examples/getRoutes-200Response-example.json
          400:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/400Response-example.json
          404:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/404Response-example.json
          500:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/500Response-example.json            
    /schedules:
      get:
        is:
          - common.transactionId
          - common.companyName
          - common.departureLocation
          - common.destinationLocation
          - common.requestTimezone
        responses:
          200:
            body:
              application/json:
                type: schedule.getSchedulesResponse
                example: !include /libraries/schedule/examples/getSchedule-200Response-example.json
          400:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/400Response-example.json
          404:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/404Response-example.json
          500:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/500Response-example.json